version: '3'
networks:
 planestic_dev:

services:
   ud-repository-publicar:
     image: planesticud/ud-repository-public:latest
     container_name: ud-repository-publicar
     restart: on-failure
     env_file:
        - .env
     networks:
        - planestic_dev          

networks:
  planestic_dev:
    external: true
